lib/eventbrite_sdk.rb, spec/eventbrite_sdk_spec.rb
For POST endpoints that take no payload (like event publishing) the payload was being set to the string "null". As a result BadRequest was being raised. The API reported that the payload was not valid JSON.
This fixes that. Don't convert the payload to JSON when it's not specified.
=> Bug Fix - do not convert nil payloads to JSON when posting

lib/eventbrite_sdk/resource/attributes.rb, lib/eventbrite_sdk/version.rb, spec/eventbrite_sdk/event_spec.rb
Just sending a TZ change with the same utc in a rich datetime field would cause the payload to just send 'timezone'. This fixes that
=> Fixing bug with changes to timezone and not utc JUST sending TZ.

lib/eventbrite_sdk/ticket_class.rb, lib/eventbrite_sdk/version.rb, spec/eventbrite_sdk/ticket_class_spec.rb
TicketClass didn't support `sales_start_after`, now it does.
=> Adding #sales_start_after support in TicketClass

lib/eventbrite_sdk/event.rb, spec/eventbrite_sdk/event_spec.rb
There is already an endpoint in the API for fetching the attendees of a particular event, so adding it to the SDK is as simple as adding the association.
Added specs based on the orders association spec, also tested locally against a real event.
=> Add ability to fetch attendees of a particular event

lib/eventbrite_sdk/event.rb, spec/eventbrite_sdk/event_spec.rb
The constant Event::CANNOT_PUBLISH was named wrong. It's value was for the cannot unpublish error type, so this corrects it's name.
=> Fix Event::CANNOT_UNPUBLISH so it has the correct value

lib/eventbrite_sdk.rb, lib/eventbrite_sdk/error_types.rb, spec/eventbrite_sdk_spec.rb
This documents and adds the common error types that the endpoints return in the response when an API exception is raised.
```ruby
begin
EventbriteSDK::Event.retrieve(id: 123)
rescue => ex
p ex.parsed_error['error']
end
EventbriteSDK::ERROR_TOKEN_REQUIRED == ex.parsed_error['error']
```
```ruby
begin
EventbriteSDK.token = 'bad_token'
EventbriteSDK::Event.retrieve(id: 123)
rescue => ex
p ex.parsed_error['error']
end
EventbriteSDK::ERROR_BAD_TOKEN == ex.parsed_error['error']
```
```ruby
begin
EventbriteSDK.token = 'good_token'
EventbriteSDK::Event.retrieve(id: 123)
rescue => ex
p ex.parsed_error['error']
end
EventbriteSDK::ERROR_NOT_FOUND == ex.parsed_error['error']
```
=> Added error type constants that are generally useful

lib/eventbrite_sdk/resource_list.rb, spec/eventbrite_sdk/resource_list_spec.rb
**What?**
This enables passing query parameters to ResourceList#retrieve.
**Why?**
It will make querying endpoints for associations with more complex endpoints cleaner and simpler. It will also do the same for querying a direct endpoint with more complex parameters.
**Compatibility**
All functionality is backwards compatible (non-breaking) and supports the paginated instance methods.
**Example**
```ruby
list = EventbriteSDK::ResourceList.new(
key: 'things',
object_class: Thing,
url_base: 'test/'
)
list.retrieve(query: { name: 'foo' })
found_things = Things.other_things.retrieve(query: { name: 'foo' })
```
=> Enable ResourceList#retrieve with custom query params

lib/eventbrite_sdk/resource/operations/list.rb, lib/eventbrite_sdk/resource_list.rb, spec/eventbrite_sdk/resource/operations/list_spec.rb, spec/eventbrite_sdk/resource_list_spec.rb
TL;DR Moving some shims over from our patched version of the SDK.
* `Resouce::Operations::List#list` now accepts an optional query argument
* `ResourceList#concat` added
* `ResourceList#to_ary` added
=> Add query option to #list operation. Add #concat, #to_ary to ResourceList

lib/eventbrite_sdk/blank_resource_list.rb, lib/eventbrite_sdk/version.rb, spec/eventbrite_sdk/blank_resource_list_spec.rb
The way we do recursive calls was exploding with the new `concat` methods since they don't exist on `BlanksResourceList`. This fixes that
=> Updating BlankResourceList to match ResourceList API

lib/eventbrite_sdk/resource.rb, lib/eventbrite_sdk/resource/operations/relationships.rb, spec/eventbrite_sdk/resource/operations/relationships_spec.rb, spec/eventbrite_sdk/resource_spec.rb
I found this while working with an object who was retrieved by a query to the API with a related object set to `expand`.
The related objects defined by `.belongs_to` suffered from 2 things:
* When the attributes have data available describing it, it was skipped and an external API call was made.
* The memoized objects were not cleared when reloaded. So if they changed they'd not be refreshed on the next call.
This fixes both of those things. 
* When the attrs have the data for the related object, it uses them.
* When #reload is called in resource, it clears the memoized values so on the next call they're refreshed.
=> Load Related From Local Data When Available

lib/eventbrite_sdk/resource_list.rb, spec/eventbrite_sdk/resource_list_spec.rb
When `page` is defined in a resource list query, it should be used. Right now it's ignored.
=> Fix ResourceList - Allow Page to be Defined in Custom Query

lib/eventbrite_sdk/resource/field.rb, spec/eventbrite_sdk/event_spec.rb, spec/eventbrite_sdk/resource/field_spec.rb
The SDK would generate changesets on rich datetime fields even if you technically did not change the value. This is problematic for activity logging in our product and needlessly pushes to v3.
Provided tests explain what this patch solves.
=> Fixing issue with rich datetime fields in payload changesets

lib/eventbrite_sdk/resource/operations/endpoint.rb, spec/eventbrite_sdk/resource/operations/endpoint_spec.rb
A resource can `#save` using an `api_token` param, but it can't `#retrieve` using one. 
This patch addresses that.
=> Threading api_token through Resource#retrieve

lib/eventbrite_sdk/resource.rb, spec/eventbrite_sdk/event_spec.rb
`EventbriteSDK::Resource.define_api_actions` did not allow an optional `:api_token`.
This fixes that
=> Adding optional :api_token passthrough to Resource.define_api_actions

README.md, lib/eventbrite_sdk/version.rb, lib/eventbrite_sdk/webhook.rb, spec/eventbrite_sdk/webhook_spec.rb, spec/fixtures/webhooks.json
Closes #31
* `Webhook` is now endowed with `Operations::List` functionality
* Documentation on how to use it
* Version bump to `3.2.0`
=> Adding Webhook#list to SDK

lib/eventbrite_sdk/resource/operations/endpoint.rb, spec/eventbrite_sdk/resource/operations/endpoint_spec.rb
changes `resource_path` allowing `:create|:update` paths.
Example:
```ruby
class Wheel < Resource
resource_path create: 'car/:car_id/wheels',
update: 'wheels/:id'
#...
end
```
The existing approach of `resource_path 'foo/:id'` still works as well.
Changes are happening internally with APIs and the public SDK needs to be prepped for this change
=> Adding ability for resources to have a different create/update path

lib/eventbrite_sdk/resource_list.rb, spec/eventbrite_sdk/resource_list_spec.rb
Some endpoints support continuated responses but there is no good way to access the data aside from checking internal state.
I exposed continuation and has_more_items so endpoints that support continuated responses will be usable.
=> Added continuation and has_more_items to ResourceList

README.md, lib/eventbrite_sdk/resource_list.rb, spec/eventbrite_sdk/category_spec.rb, spec/eventbrite_sdk/event_spec.rb, spec/eventbrite_sdk/lists/owned_event_orders_list_spec.rb, spec/eventbrite_sdk/order_spec.rb, spec/eventbrite_sdk/resource_list_spec.rb, spec/eventbrite_sdk/subcategory_spec.rb, spec/eventbrite_sdk/webhook_spec.rb
- Support for continuations through `ResourceList#continue`
- Adds continuation documentation
- Removed auto appending of `?page=1` on initial requests of `ResourceList`s
Addresses community ask: https://github.com/eventbrite/eventbrite-sdk-ruby/pull/35#issuecomment-435191744
=> Adding SDK support for continuations

.gitignore, eventbrite_sdk.gemspec, lib/eventbrite_sdk.rb, lib/eventbrite_sdk/discount.rb, lib/eventbrite_sdk/discounts_list.rb, lib/eventbrite_sdk/organization.rb, lib/eventbrite_sdk/organization_entities.rb, lib/eventbrite_sdk/version.rb, spec/eventbrite_sdk/discount_spec.rb, spec/eventbrite_sdk/lists/discounts_list_spec.rb, spec/eventbrite_sdk/organization_spec.rb, spec/support/endpoint_request_matchers.rb
Added the new entities to support organization API requests. This isn't complete but it get's us moving forward.
https://www.eventbrite.com/platform/api#/reference/event/list/list-events-by-organization
https://www.eventbrite.com/platform/api#/reference/venue/list/list-venues-by-organization
https://www.eventbrite.com/platform/api#/reference/discount/search-discounts-by-organization
- Discount
- DiscountsList
- Organization
- OrgDiscount
- OrgEvent
- OrgVenue
- Added ruby version file for rbenv
- Bumped bundler dependency
- Updated our request matchers to remove use of deprecated methods
=> [MINOR] Add Discounts, Organization and its entities

lib/eventbrite_sdk/resource/schema_definition.rb, lib/eventbrite_sdk/venue.rb, spec/eventbrite_sdk/resource/schema_definition_spec.rb
This adds address as a supported schema type per the EB basic types.
https://www.eventbrite.com/platform/api#/introduction/basic-types/address
This also sets us up to support the many attendee addresses that the attendee endpoint supports.
=> [MINOR] Add address type to resource schema definition
